### ISSUE TITLE
backtest fill logic

### ISSUE THREAD

**Issue by orens77** [opentradesolutions/opentrade#10]
I was looking at a backtest simulation for a simple algo and I noticed an unexpected situation where I had sell limit orders with e.g. qty 100 price $99.00 and qty 100 price $100.00 both on the book at the same time and then I saw the $100 sell order filled with the $99 sell order sitting unfilled.  I think the problem is that the order of iteration through active orders in the functions TryFillBuy and TryFillSell should be reversed.  Am I missing something?

**Comment by open-trade** [comment]
yes, you are right, could you
please submit a pull request? i
am on the travel lately, inconvenient to write code. thank you.

**Comment by orens77** [comment]
Sure, I will submit one for this.  

The other issue I noticed when looking into this is that the use of adjustments for volume/size can lead to valid qty values in the range 0 < qty < 1 in the bid/ask/last sizes.  The problem is that when the base class MarketDataAdaptor::Update functions get called they implicitly cast the size / last_qty values to integral types.  When those functions get a zero value they treat it as missing and so the market data does not update properly.  
So for this tick sequence:

120101012 0 T 138.5 200
120102903 0 T 138.58 1
120103202 0 T 138.5 100

with a 1:2 split, instead of seeing:
  100 @ 277.0 
0 or 0.5 @ 277.16
  50 @ 277.0
the market data will show
  100 @ 277.0
  100 @ 277.16
  50 @ 277.0

This should rarely come up with most instruments but I'm looking at some strange stuff.  
I added the following to market_data.h:
```c++
#ifdef BACKTEST
typedef double qty_t;
typedef double volume_t;
#else
typedef int qty_t;
typedef uint64_t volume_t;
#endif
```
then used the qty_t and volume_t types in the definitions of MarketData::Trade and MarketData::Quote and propagated those changes through the code.  

I will back these changes out for this pull request.  If you want me to do anything with them please let me know.

**Comment by open-trade** [comment]
ok, please typedef in marketdata structure and use int64_t, it  looks wierd one is signed , the other is not
