### ISSUE TITLE
Question about roadmap

### ISSUE THREAD

**Issue by orens77** [opentradesolutions/opentrade#13]
Are there plans for any of the following?

tracking transaction fees / commissions

tracking balances by account and currency

interface for tracking derived data from tick streams, e.g., 1-minute or 5-minute bars

**Comment by open-trade** [comment]
tracking transaction fee and commission can be done via openrisk. i guess balance can also be done via openrisk though it is post trade check.  openrisk is quite flexible. as for data interface to compute from tick data and share between algos, i have been thinking about it, so far not got a good idea.

**Comment by open-trade** [comment]
if you have some idea, we can discuss

**Comment by open-trade** [comment]
I just added derived data support in latest commit, but not test yet, you can try out.

**Comment by orens77** [comment]
This is where I am stuck on how to implement modular "derived data"

In order for (some) derived data to work properly, it should have a chance to process every tick.  
Currently the MarketDataManager::Update routines call  AlgoManager::Update(src, id) on every tick, but to keep things light and fast and to avoid blocking and filling up buffers this only notifies each Algo that the data has changed and the algo may not have a chance to run on every tick.  

In order to implement a DerivedData object that does process every tick it seems we need either to subclass the MarketDataAdapter and plug into the Update functions (probably bad idea) or we need to add a DerivedDataManager that has an opportunity to distribute the market-data update data to DerivedData objects like the AlgoManager but passing the updated data in each function call.  

Does the second option seem feasible?

**Comment by open-trade** [comment]
I think you should start from current snapshot based stream. if you see any serious problem which can not be avoided, then we can try out tick by tick derivedmanager.
星期一, 25 三月 2019, 00:31上午 +08:00 发件人 orens77  notifications@github.com :

**Comment by orens77** [comment]
I like what you've done with the SetIndicator / GetIndicator on the MarketData struct, and I agree that the whole separate manager is overkill.  May I suggest a simple extension that solves my issue:  

in `MarketData`

```c++17
  struct Indicator {
    typedef void (*OnTradeHook)(const MarketData&, double /*price*/, Qty /*qty*/);
    typedef void (*OnQuoteHook)(const MarketData&, double /*price*/, Qty /*qty*/,
                                bool /*is_bid*/, uint32_t /*level*/);
    std::any value;
    OnTradeHook OnTrade = nullptr;
    OnQuoteHook OnQuote = nullptr;
  }

  void SetIndicator(Indicator indicator, size_t id) {
     ...
  }
```

And then in `MarketDataAdapter::Update` simply run through the indicators and call any hooks that are not null just before calling Update on the AlgoManager instance.  

For simple indicators (like 1-minute bars) this should not cause too much overhead, and it should still support using the same structures with more complicated functions accessed via the Algo routines in other threads that are not necessarily called on every tick.

**Comment by open-trade** [comment]
I am writing BarIndicator, as our client requested, it will be builtin indicator, it will not miss trade tick. I do not think anyone really need an QuoteHook.

**Comment by open-trade** [comment]
Good idea. I will add OnTradeHook

**Comment by open-trade** [comment]
the problem is if there are 100 indcators, we need iterate 100 times every tick even most of indicator has empty hook. i also do not like to add another queue and notify all.

**Comment by orens77** [comment]
Agree that too many indicators using the hook callback is problematic...
 for my purposes 1 or 2 indicators per subscription need to be called with
the OnTradeHook.  Leaving that as a function pointer in the struct keeps
overhead low even when additional indicators (that do not use the hook) are
present — checking for null pointer is fast.

Additional indicators for me, if needed, can be built from the outputs of
the 1 or 2 called on each tick and those can be built from snapshot data
without loss of accuracy.

Main alternative for me involves duplicating the tick feed and aggregating
the indicator data in a separate process alongside opentick which is
possible but equally problematic.

End of the day it is your project and your call — I think it is very good
work and I am happy to use it and contribute if I can.  My suggestions are
simply suggestions.

**Comment by open-trade** [comment]
do you really need quote tick? i am currently solving trade tick issue per client requirement because they need minutes bar. your hook idea is good, i am still looking for a good solution, do not have to put hook one every indicator body. please check tommorrow, you may see a solution i give in the code.

**Comment by orens77** [comment]
I do not need the callback for each quote update.  The trade tick callback is sufficient for me as well.  Thank you

**Comment by orens77** [comment]
Looks like you've made a lot of good progress and I look forward to testing it out soon.

one little performance note:

https://github.com/opentradesolutions/opentrade/blob/0901b48fe6500c93e349e98901eeac872a795292/src/opentrade/market_data.h#L120

I suggest delaying construction of the shared_lock in the Check function until after checking for null mngr_  --  null pointer check is very fast but shared_lock creation is not.

**Comment by open-trade** [comment]
good input. can i know which markets will you use it for, and which security types?

**Comment by orens77** [comment]
Focusing on equities and FX, but still building and testing.  Open to various markets but not yet ready for trading.

**Comment by open-trade** [comment]
please check barindicator, and algos/alphasample.py which subscribes to barindicator

**Comment by orens77** [comment]
Thank you, I will.  I am traveling for a week so I will not have much opportunity to do real testing until the 7th but it's near the top of my todo list when I return.

**Comment by open-trade** [comment]
have a good travel.

**Comment by orens77** [comment]
I'm don't think I understand why you chose to make IndicatorHandler a subclass of Algo.   
I'm currently getting assertion failures when I try to use more than one algo_threads:

```
opentrade: src/opentrade/algo.cc:24: void opentrade::AlgoRunner::operator()(): Assertion `std::this_thread::get_id() == tid_' failed.

opentrade: src/opentrade/algo.cc:74: void opentrade::AlgoManager::Register(opentrade::Instrument*): Assertion `std::this_thread::get_id() == runner.tid_' failed.
```

**Comment by open-trade** [comment]
for writing less codeOn Apr 11, 2019 04:47, orens77 <notifications@github.com> wrote:I'm don't think I understand why you chose to make IndicatorHandler a subclass of Algo.
I'm currently getting assertion failures when I try to use more than one algo_threads:
opentrade: src/opentrade/algo.cc:24: void opentrade::AlgoRunner::operator()(): Assertion `std::this_thread::get_id() == tid_' failed.

opentrade: src/opentrade/algo.cc:74: void opentrade::AlgoManager::Register(opentrade::Instrument*): Assertion `std::this_thread::get_id() == runner.tid_' failed.

**Comment by open-trade** [comment]
do need refactoryOn Apr 11, 2019 08:10, OpenTrade <info@opentradesolutions.com> wrote:for writing less codeOn Apr 11, 2019 04:47, orens77 <notifications@github.com> wrote:I'm don't think I understand why you chose to make IndicatorHandler a subclass of Algo.
I'm currently getting assertion failures when I try to use more than one algo_threads:
opentrade: src/opentrade/algo.cc:24: void opentrade::AlgoRunner::operator()(): Assertion `std::this_thread::get_id() == tid_' failed.

opentrade: src/opentrade/algo.cc:74: void opentrade::AlgoManager::Register(opentrade::Instrument*): Assertion `std::this_thread::get_id() == runner.tid_' failed.

**Comment by open-trade** [comment]
> I'm currently getting assertion failures when I try to use more than one algo_threads:
> 
> ```
> opentrade: src/opentrade/algo.cc:24: void opentrade::AlgoRunner::operator()(): Assertion `std::this_thread::get_id() == tid_' failed.
> 
> opentrade: src/opentrade/algo.cc:74: void opentrade::AlgoManager::Register(opentrade::Instrument*): Assertion `std::this_thread::get_id() == runner.tid_' failed.
> ```

fixed

**Comment by orens77** [comment]
The indicators are working nicely, thank you.

**Comment by open-trade** [comment]
@orens77 How is your project going on? Anything we can do help? you can contact me by info@opentradesolutions.com
