### ISSUE TITLE
currency field in FIX

### ISSUE THREAD

**Issue by orens77** [opentradesolutions/opentrade#14]
https://github.com/opentradesolutions/opentrade/blob/99ffc6a365a47005af9d6c43dc3474cd9e59fa46/src/fix/fix.h#L296

I believe this field is for the QUOTE currency which is the value in the sec->currency column;

Forex trades entirely different order types in FIX

**Comment by open-trade** [comment]
ok

**Comment by orens77** [comment]
If I want to place a limit order to buy $1000.00 USD using EUR, with the security fields as follows (from the database):

symbol = USDEUR
currency = EUR
rate = 1.16509379005009905
close_price = 0.858299999999999952

My understanding is that I should set the following FIX fields (for 4.2):

OrdType<40> = 2 // Limit   (or = F // Forex-Limit)
Side<54> = 1 // Buy
Symbol<55> = "USDEUR"  // I usually see this as "USD/EUR"
OrderQty<38> = 1000
Price<44> = 0.8900
Currency<15> = "EUR"
// FIX 4.4 also has Product<460> = 4 // Currency

This also seems natural for other securities e.g. US Equities have currency = "USD" and HK equities have currency = "HKD"  

If I am reading something incorrectly, please let me know.

**Comment by open-trade** [comment]
you can use eurusd pair

**Comment by open-trade** [comment]
there is no eurusd pair in db, but you can add yourself

**Comment by open-trade** [comment]
this link https://stackoverflow.com/questions/30045142/fx-forex-currency-fix-tag-54-how-to-use-it may help you
