### ISSUE TITLE
sim_server fill logic

### ISSUE THREAD

**Issue by orens77** [opentradesolutions/opentrade#15]
https://github.com/opentradesolutions/opentrade/blob/07e1b42bbaadd277dbb7dffec1ee7be1f5f5c5e1/src/fix/sim_server.cc#L182

This should also go through the active orders in order of increasing price and age for limit sells and decreasing price for limit buys.
I noticed you recently made the Simulator class modular for backtest -- perhaps it makes sense to plug that in to the live sim too?  

Thanks

**Comment by open-trade** [comment]
yes, but this is not urgent, sim-server just for demo, not that important.
