### ISSUE TITLE
[FAQ] : What exactly is the meaning of term BOD ?

### ISSUE THREAD

**Issue by karan-k-deepr** [opentradesolutions/opentrade#21]
Your code is really well written with the implementation of all required functionalities, and I am enjoying reading it. But there is a term BOD in `position.h` at `line: 42`, this term is quite new to me. Can you please give me some detail introduction os this term, just for my knowledge?

**Comment by alphamodel** [comment]
Similar to [EOD](https://en.wikipedia.org/wiki/End_of_day), it means beginning of day.
