### ISSUE TITLE
Exchange interface

### ISSUE THREAD

**Issue by mg64ve** [opentradesolutions/opentrade#22]
Hi nice project.
Thanks for sharing.
Is this for FIX market only?

**Comment by open-trade** [comment]
please check src/adapters，write your own market connectivity

**Comment by mg64ve** [comment]
Thanks, I will.
One more question. When I run opentrade, tick data file can be replaced by data of any granularity? 1 min data for instance?

**Comment by open-trade** [comment]
no, it is tick by tick
