### ISSUE TITLE
where are the code of web gui?

### ISSUE THREAD

**Issue by royburns** [opentradesolutions/opentrade#7]
thanks for your inviting through the email.
but where are the raw code of the web gui?
i just see the compress version in the folder '.\web' as below:

index-569f490e0a3e1e876b31.bundle.js
index-8563627080dc058da106.css

**Comment by open-trade** [comment]
not open source yet

**Comment by jandykwan** [comment]
in fact the web ui is not secret, why not open source, as we may want to do some modification, thanks

**Comment by open-trade** [comment]
sorry

--------------原始邮件--------------
发件人："jandy "<notifications@github.com>;
发送时间：2019年3月4日(星期一) 下午2:16
收件人："opentradesolutions/opentrade" <opentrade@noreply.github.com>;
抄送："open-trade "<info@opentradesolutions.com>;"State change "<state_change@noreply.github.com>;
主题：Re: [opentradesolutions/opentrade] where are the code of web gui? (#7)
-----------------------------------

 
in fact the web ui is not secret, why not open source, as we may want to do some modification, thanks
